direction: down

Client: Client: Chrome, Firefox, etc..
Server: Server: Apache, Nginx, etc..

Client -> Server: 1.Give me the website!
Server -> Client: 2.HTML
Server -> Client: 3.CSS
Server -> Client: 4.JS

